### PR TITLE
Encode and decode PID in the new format.

### PR DESCRIPTION
**Pull request by losfair**
Since OTP 23 the distribution flag `DFLAG_BIG_CREATION` became [mandatory](https://erlang.org/doc/apps/erts/erl_ext_dist.html#NEW_PID_EXT) and now all PIDs are encoded in the new ` NEW_PID_EXT` format.

### CODE REVIEW

**Review by sile — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by sile** [comment]
Oops, some tests failed. Could you fix that?

**Comment by losfair** [comment]
Fixed! Also added a new assertion for the new PID format.

**Comment by sile** [comment]
Thank you!

**Pull request merged**
